name: testtrinity
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get:
  flutter:
    sdk: flutter
  avatars: ^3.0.2
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  intl: any
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  mocktail: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_app_launch.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
